apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 5001

---
apiVersion: apps/v1
kind: Pod
metadata:
  name: product

spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: jdst103/product-service:initial
        ports:
        - containerPort: 80
